### ISSUE TITLE
Issue with depreciated package 

### ISSUE THREAD

**Issue by whitecodes001** [LuigiVampa92/merge-apks#1]
DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.spawn import find_executable

**Comment by LuigiVampa92** [comment]
Hi, thanks for the interest to the project!

Yes, find_executable function was used to check if apktools is available on the machine running the script. Not sure why I decided to use it at the point when I published the script, but I have just replaced that deprecated call with distutils.spawn, which effectively does the same and should not throw any warnings on the modern python versions.

Thanks again for your attentiveness
